site_name: Django Hatchway
site_description: An unsurprising Django API framework
repo_name: andrewgodwin/django-hatchway
repo_url: https://github.com/andrewgodwin/django-hatchway

theme:
  name: material
  logo: img/logo.png
  favicon: img/logo.png
  palette:
    - scheme: default
      primary: black
      accent: light blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
          icon: material/lightbulb-outline
          name: Switch to light mode
  features:
  - navigation.footer
  - search.suggest
  - search.highlight
  - content.tabs.link
  icon:
    repo: fontawesome/brands/github-alt
  language: en
plugins:
- search

nav:
- Django Hatchway: index.md
- Tutorial - User Guide: tutorials/user_guide.md

markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- mdx_include:
    base_path: docs
- admonition
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tabbed:
    alternate_style: true
- attr_list
- md_in_html
extra_css:
- css/termynal.css
- css/custom.css
extra_javascript:
- js/termynal.js
- js/custom.js