name: Test

on:
  push:
  pull_request:

jobs:
  test:
    name: test py${{ matrix.python-version }} with ${{ matrix.db_name }}
    runs-on: ubuntu-latest
    timeout-minutes: 8
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: |
          python -m pip install -e .[test] pre-commit
      - name: Run pytest
        run: |
          python -m pytest
#      - name: Run pre-commit
#        run: |
#          pre-commit run -a --show-diff-on-failure
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
          cache-dependency-path: pyproject.toml
      - uses: actions/cache@v3
        id: pip-cache
        with:
          key: ${{ env.pythonLocation }}
          path: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
      - name: Install dependencies
        run: pip install -e .[doc]
      - name: Build docs
        run: mkdocs gh-deploy --force
